new commit
kertio/frontend_course_rep1 pull request #4
Opened 2023-08-09 11:38 UTC by kertio

2023-08-11 06:22 UTC, Grinv requested changes

2023-08-11 06:22 UTC, Grinv commented on 1-Blog/index.html
> +	<title>Blog</title>
Тут же весь контент на русском) Давай и title на русском сделаем. Тем более у тебя прописано `lang="ru"`

И ещё хорошая привычка с title сразу добавлять description
```html
<meta name="description" content="Описание страницы" />

2023-08-11 06:22 UTC, Grinv commented on 1-Blog/index.html
> +	<section>
Стандартная схема такая:
```html
<header />
<main />
<footer />
```
Оберни пожалуйста в `main`

2023-08-11 06:22 UTC, Grinv commented on 1-Blog/index.html
> +		<div>
Зачем тут div?

2023-08-11 06:22 UTC, Grinv commented on 1-Blog/index.html
> +		<h2>Теория цвета - Как цвет влияет на поведение потребителей</h2>
А где h1?

2023-08-11 06:22 UTC, Grinv commented on 1-Blog/index.html
> +	<section>
section без заголовка не бывает
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section
>Sections should always have a heading, with very few exceptions.

2023-08-11 06:22 UTC, Grinv commented on 2-Form/index.html
> +		<h2>Уже есть аккаунт?<a href="#">Войти</a></h2>
Это точно не заголовок) Либо в `p`, либо в `div`

2023-08-11 06:22 UTC, Grinv commented on 2-Form/index.html
> +	<title>Form</title>
По title теже комменты, что и в соседней задаче

2023-08-11 06:22 UTC, Grinv commented on 2-Form/index.html
> +			<input type="text" name="company" placeholder="Моя компания">
Так можно просто в label обернуть)
```html
<label>
   Моя компания
   <input type="text" name="company" placeholder="Моя компания">
</label>

2023-08-11 06:22 UTC, Grinv commented on 2-Form/index.html
> +			<button>Зарегистрироваться<span>&rarr;</span></button>
Тут не нужен span

2023-08-11 06:22 UTC, Grinv commented on 2-Form/index.html
> +				<input type="email" name="email" placeholder="E-mail">
type="email" - это молодец) Это вообще хорошая привычка, потому что на мобилках тип клавиатуры от него зависит
![image](https://github.com/kertio/frontend_course_rep1/assets/4070730/73ee7e63-0c6f-4309-a9ae-0de5ef8f5a4c)

2023-08-11 06:22 UTC, Grinv commented on 2-Form/index.html
> +				<input type="text" name="name" placeholder="Имя">
Очень хорошей привычкой является подставлять autocomplete. Там огромный набор вариантов, вплоть до автоподставления данных кредитной карты. Пусть браузер делает работу за юзера, юзеру это будет приятно)
Cписок можно поизучать тут: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2023-08-11 06:22 UTC, Grinv commented on .gitignore
> +forms.txt
Не вижу этого файла

2023-08-11 08:20 UTC, kertio commented on 1-Blog/index.html
> +		<div>
У меня не получалось чтобы блок "<p>FRONTEND<span>&deg;</span>12 мая 2024</p>" был на новой строке. исправил )

2023-08-11 10:28 UTC, kertio commented on .gitignore
> +forms.txt
в нем я записывал по ходу видеоуроков теги и их описание, заметки.. могу добавить)

2023-08-14 06:49 UTC, Grinv commented on .gitignore
> +forms.txt
Можешь тогда добавить файл в .gitignore
Он будет лежать в папке, но никак не будет восприниматься гитом

2023-08-14 06:50 UTC, Grinv approved these changes

2023-08-14 06:50 UTC, Grinv commented on 2-Form/index.html
> +					E-mail</label>
Закрывающий тэг лэйбла не там стоит)

2023-08-14 06:50 UTC, merged

2023-08-14 08:36 UTC, kertio commented on 2-Form/index.html
> +					E-mail</label>
упс.. )