2 css
kertio/frontend_course_rep1 pull request #6
Opened 2023-08-14 14:26 UTC by kertio

2023-08-17 07:36 UTC, Grinv requested changes

2023-08-17 07:36 UTC, Grinv commented on 1-Blog/index.html
> +				<a href="#">Мой блог</a>
Зачем дробить на две ссылки?)
Можно ж в одну объединить
```html
<a href="#">
   <span class="logo-symbol">B</span>
   Мой блог
</a>

2023-08-17 07:36 UTC, Grinv commented on 1-Blog/index.html
> +			<span class="frontend-info__circle"></span>
Для текущего уровня сложновато, но на будущее) Лучше такие элементы делать через псевдо-элементы after и before. Как пример: https://codepen.io/clivewalker/pen/eZWxrm

2023-08-17 07:36 UTC, Grinv commented on 1-Blog/styles/style.css
> +	width: 525px;
А теперь попробуй сузить окно браузера,  потихоньку начинай думать про адаптивность вёрстки, как оно будет вести себя на мобилках. Это супер полезная привычка)
В данном случае лучше использовать:
```css
max-width: 525px;

2023-08-17 07:36 UTC, Grinv commented on 1-Blog/styles/style.css
> +.developer-info__image {
Так `.developer-info img` или `.developer-info__image`? Давай всё-таки одним путём будет действовать

2023-08-17 07:36 UTC, Grinv commented on 2-Form/index.html
> +					id="email"
Тут id не нужен

2023-08-17 07:36 UTC, Grinv commented on 2-Form/styles/style.css
> +#label__company imput {
TYPE не imput, а input
Кажется, оно и не работает, если не заметил)

2023-08-17 07:36 UTC, Grinv commented on 2-Form/styles/style.css
>  h2 a {
Всё-таки лучше приучить себя стилизовать через классы. На такой маленькой странице окей. Но на будущее, когда страницы усложнятся, появится много элементов, там только через классы. Поэтому лучше приучить себя сразу)

2023-08-17 07:36 UTC, Grinv commented on 1-Blog/styles/style.css
> +.paragraph-text__block1 {
Можно через селектор 
```css
.paragraph-text:first-child {}

2023-08-17 08:13 UTC, kertio commented on 1-Blog/index.html
> +				<a href="#">Мой блог</a>
О, а этого я не знал) Этого и хотел добиться изначально, не получалось. )

2023-08-17 08:15 UTC, kertio commented on 1-Blog/index.html
> +			<span class="frontend-info__circle"></span>
Аналогично предыдущему, хотел сделать через after, но то что я сделал, не то чего я хотел, оставил пока так, до лекций где про позиционирование будет объясняться, добавил сначала, всё разъехалось, только испортил, потому и решил оставить)

2023-08-18 02:04 UTC, kertio commented on 1-Blog/styles/style.css
> +.paragraph-text__block1 {
Не совсем понял как правильно сделать. В разметке три параграфа, все они в main. Ко всем параграфам я применил стили для тега p, а параграфу где нужно было изменить размер шрифта, применил уже стили через класс paragraph-text__block1. Могу переделать чтобы только через классы стилизовать :)

2023-08-21 08:42 UTC, Grinv requested changes

2023-08-21 08:42 UTC, Grinv commented on 1-Blog/index.html
> +			<div class="logo">
Нет закрывающего div

2023-08-21 08:42 UTC, Grinv commented on 1-Blog/index.html
> +			<div class="logo">
А нужна ли тут впринципе обёртка из div? У тебя дальше идёт ul и он блочный и явно перенесётся. Я бы избавился от вложенности
```html 
<nav>
   <a href="#" class="logo">
      <span class="logo-symbol">B</span>
      Мой блог
   </a>
   <ul>...</ul>
</nav>

2023-08-21 08:42 UTC, Grinv commented on 1-Blog/index.html
> +			<span>FRONTEND</span><span>12 мая 2024</span>
Если что, для дат и времени существует классный тэг `time` 😉
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

2023-08-21 08:42 UTC, Grinv commented on 1-Blog/styles/style.css
> +	padding: 10px 10px;
Тогда просто 
```css
padding: 10px;

2023-08-21 08:42 UTC, Grinv commented on 1-Blog/styles/style.css
> +	max-width: 525px;
У тебя тут просто хаос такой из обозначений. Есть и `vw` и `rem` и `em` и `px`. Сам то не запутаешься? :)
Советую всё-таки прийти к подходу применять минимум обозначений :)

2023-08-21 08:42 UTC, Grinv commented on 1-Blog/styles/style.css
> +.frontend-info > span:nth-child(1)::after {
С псевдо-классами - молодец. Тут также можно применить `:first-child`

2023-08-21 08:42 UTC, Grinv commented on 1-Blog/styles/style.css
> +.paragraph-text__block1 {
Я советую выносить общие свойства в один класс, ну либо мультипликатором пользоваться, это как тебя удобнее
```css
.paragraph-text__block {
   width: 100%;
   max-width: 525px;
}
```
либо через мультипликатор:
```css
.paragraph-text__block1, .paragraph-text__block2 {
   width: 100%;
   max-width: 525px;
}
```
а потом частные прописывать через модификатор:
```css
.paragraph-text__block_first {
   font-size: 2rem;
   margin-bottom: 35px;
}

.paragraph-text__block_last {
   font-size: 2rem;
   margin-bottom: 35px;
}
```
либо так
```css
.paragraph-text__block:first-child {
   font-size: 2rem;
   margin-bottom: 35px;
}

.paragraph-text__block:last-child {
   font-size: 2rem;
   margin-bottom: 35px;
}
```
Опять же, стили надо делать более гибкими и думать наперёд. А что если появится 3 параф? И 4? Как прописать стили так, чтоб они работали универсально не в завимости от количества параграфов?
Например `margin-bottom: 35px;` можно прописать так:
```css
.paragraph-text__block:not(:last-child) {
   margin-bottom: 35px;
}
```
тогда у тебя правило будет работать для всех параграфов, кроме последнего :)

2023-08-21 08:42 UTC, Grinv commented on 2-Form/index.html
> +			<p class="title">Регистрация</p>
У тебя тут заголовком явно является "Регистрация" :)
"Уже есть аккаунт?" - это просто текст)

2023-08-21 08:42 UTC, Grinv commented on 2-Form/index.html
>  						autocomplete="organization">
👍

2023-08-21 08:42 UTC, Grinv commented on 2-Form/index.html
> +					<input class="input-company"
Я бы сказал, что input - это элемент, а company, name, surname - это модификаторы. Т.е. лучше задавать так:
`input_company`, `input_name`

2023-08-21 08:42 UTC, Grinv commented on 2-Form/index.html
>  						placeholder="Имя"
На будущее - у тебя уже есть label - это хорошо
В placeholder вставлять тоже самое - не имеет большого смыла. Можно вставить какой-то пример. Или подсказу
Есть классная статья на эту тему https://htmlacademy.ru/blog/html/form-design-placeholders

2023-08-21 08:42 UTC, Grinv commented on 2-Form/index.html
> +					<input class="input-name"
`autocomplete="given-name"`

2023-08-21 08:42 UTC, Grinv commented on 2-Form/index.html
> +					<input class="input-surname"
`autocomplete="family-name"`

2023-08-21 08:42 UTC, Grinv commented on 2-Form/styles/style.css
> +	background-color: #02577cee;
Это что за странный цвет такой?)

2023-08-21 08:42 UTC, Grinv commented on 2-Form/styles/style.css
> +	margin: 0 0 22px;
Кажется, тут можно обойтись только margin-bottom
```css
margin-bottom: 22px;

2023-08-21 08:42 UTC, Grinv commented on 2-Form/styles/style.css
>  	font-family: 'Open Sans', sans-serif;
Стиль шрифта прописал. Но не увидел, чтоб подключил сам шрифт)

2023-08-21 08:42 UTC, Grinv commented on 2-Form/styles/style.css
> +	background: url('../icons/arrow.svg');
Молодец, что через ::after! Круто :)

2023-08-27 10:00 UTC, Grinv approved these changes

2023-08-27 10:00 UTC, Grinv commented on 1-Blog/index.html
> +			<label class="search">
Поиск не является частью навигации, поэтому лучше из блока nav достать

2023-08-27 10:00 UTC, merged