3 flex
kertio/frontend_course_rep1 pull request #7
Opened 2023-08-24 06:26 UTC by kertio

2023-08-27 11:51 UTC, Grinv requested changes

2023-08-27 11:51 UTC, Grinv commented on 1-Blog/styles/style.css
> +	max-width: 1080px;
Это ограничение лучше перенести в .header. А то придётся каждому элементу указывать ограничение

2023-08-27 11:51 UTC, Grinv commented on 1-Blog/styles/style.css
> +	padding: 80px 0;
Всё-таки этот спейс не является часть .nav. Поэтому лучше это сделать либо так:
```css
.header {
   padding: padding: 80px 0;
}
```
либо так
```css
.nav {
   margin: 80px auto;
}

2023-08-27 11:51 UTC, Grinv commented on 1-Blog/styles/style.css
> +	margin-right: 77px;
Лучше это сделать, как gap у .nav

2023-08-27 11:51 UTC, Grinv commented on 1-Blog/styles/style.css
> +	margin-right: auto;
По-хорошему, нам надо будет перед этим скинуть дефолтный спейс для всех ul
```css
ul {
   margin: 0;
}

2023-08-27 11:51 UTC, Grinv commented on 1-Blog/styles/style.css
> +	margin: 0 10px;
Нам тут margin слева не нужен, поэтому лучше так:
```css
margin-right: 10px;
```
Ну а вообще `.logo` можно было сделать тоже через flex и сделать `gap: 10px`

2023-08-27 11:51 UTC, Grinv commented on 2-Form/styles/style.css
> +	box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
![Screenshot 2023-08-27 at 19 31 43](https://github.com/kertio/frontend_course_rep1/assets/4070730/cc60fcb9-6dd2-4d31-86ad-d4ea3eedd2eb)
А что это за полоска внизу?
Т.к. background применяется для всей страницы, советую навесить его на body

2023-08-27 11:51 UTC, Grinv commented on 2-Form/styles/style.css
> +	margin: 225px auto;
Не, ну так центрировать никуда не годится. Почитай о том, как мы можем центрировать элементы. Раз мы узнали про flex, то есть возможность центрировать через flex :)

2023-08-27 11:51 UTC, Grinv commented on 2-Form/styles/style.css
> +	max-width: 383px;
Зачем? У нас есть ограничение ширины у самой формы

2023-08-27 11:51 UTC, Grinv commented on 2-Form/styles/style.css
> +	margin: auto;
А это зачем?

2023-08-27 11:51 UTC, Grinv commented on 2-Form/styles/style.css
> +	margin: auto;
А это зачем?)

2023-08-27 11:51 UTC, Grinv commented on 2-Form/styles/style.css
> +	width: calc(100% / 2 - 2px);
У тебя по всей форме одинаковые спейсы. Давай сделаем сетку из flex. Для этого надо будет:
1) Вытащить заголовок и `.form-subtitle` из `form`
2) Сделать form `display: flex`
3) Установить `gap`
4) Для `reg-names` убрать свойство `width` и добавить `flex: 0.5`

2023-08-27 16:02 UTC, kertio commented on 2-Form/styles/style.css
> +	box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
Полоска это от градинта страницы. Градиент в боди и так находится. Выделенный фрагмент кода это обводка самого блока "регистрация" :-)

2023-08-31 17:42 UTC, Grinv approved these changes

2023-08-31 17:42 UTC, Grinv commented on 2-Form/styles/style.css
> +	box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
Так тебе надо, что градиент был во всю высоту окна браузера) Поправь пожалуйста в следующем ревью

2023-08-31 17:42 UTC, Grinv commented on 1-Blog/styles/style.css
> +	padding: 0;
Внимательнее, я писал `margin: 0` :))

2023-08-31 17:42 UTC, merged