4 final
kertio/frontend_course_rep1 pull request #8
Opened 2023-09-14 01:17 UTC by kertio

2023-09-30 04:02 UTC, Grinv commented
Горизонтальный скролл. Это не есть хорошо. Всегда за этим внимательно следи)
![Screenshot 2023-09-30 at 12 01 38](https://github.com/kertio/frontend_course_rep1/assets/4070730/2a28772e-b9f6-4e5f-8845-cc895c21fc17)

2023-09-30 05:40 UTC, Grinv requested changes

2023-09-30 05:40 UTC, Grinv commented on 3-finio/css/global.css
> +	cursor: url('../images/cursor.png'), auto;
Зачем кастомный курсор?) Лучше устанавливай, который пользователю привычен - это первое. Второе - он у тебя в png и детальность курсора не такая высокая. Например, на ретине мака смотрится вообще не очень
Установи просто `cursor: pointer`
Лучше впринципе пользоваться системными курсорами, которые привычны пользователю, если это не совсем что-то специфичное

2023-09-30 05:40 UTC, Grinv commented on 3-finio/css/global.css
> +	max-width: calc(var(--container-width) + (var(--padding-container) * 2));
Не совсем понял, зачем такая сложность в расчётах?)
Есть прекрасное свойство `box-sizing: border-box`, которое учитывает не только высоту/ширину, но и отступы. Можешь почитать подробнее тут: https://css-tricks.com/box-sizing
Так что можно переписать:
```css
width: 100%;
max-width: var(--container-width);
box-sizing: border-box;
```

2023-09-30 05:40 UTC, Grinv commented on 3-finio/css/components/logo-list.css
> +	margin-right: 10px;
Не стоит игнорить gap, это прекрасная фича)
Так что лучше убрать отсюда margin-right и в .logo-list добавить `column-gap: 10px`

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +		<div class="container header__wrapper d-flex-row-sb">
Тебе не нужен тут div :)
Пропиши просто
```html
<header class="header container header__wrapper d-flex-row-sb">
```
И тебе всего-лишь в header надо будет добавить 
```css
    padding-top: 40px;
    padding-bottom: 96px;

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +	<div class="header-skewed-bg">xcv</div>
А это что за артефакт?)

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +	<link rel="stylesheet" href="./css/main.css	">
Лишний пробел

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +						<a href="#!" class="nav__link">Поддержка&nbsp;клиентов</a>
Если тебе нужно, чтоб слова не переносились и всё было в одну строку - можно использовать не неразрывные проблемы, а прекрасное свойство `text-wrap: nowrap`  :)

Есть прям классическая связка, если надо обрезать фразу, которая не вмещается в строку.
```css
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +			<button class="burger"></button>
```html
<button class="burger" />
```

Но я бы всё-таки рекомендовал сюда вставить чилдрена

```html
<button>
   <img src="../../images/icons/burger.svg" />
</button>

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +					<h1 class="title-h1">Простой финансовый учёт для продавцов на маркетплейсах</h1>
Советую воспользовать `text-wrap: balance`
Супер крутое свойство и мне очень нравится. Появилось совершенно недавно и мало, какими браузерами поддерживается, Но хуже точно не сделает :)
Почитать можно тут: https://developer.chrome.com/blog/css-text-wrap-balance

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +		<ul class="container features-list">
![Screenshot 2023-09-30 at 12 47 54](https://github.com/kertio/frontend_course_rep1/assets/4070730/452d8f53-50c1-42b4-a5ed-8e520d5acc11)
Чтоб вот такого не было, что разная ширина, а было ровненько и красиво:
![Screenshot 2023-09-30 at 12 50 55](https://github.com/kertio/frontend_course_rep1/assets/4070730/849d0d65-5597-4a0d-be5b-d124b02011ef)
Можно сделать так:
```css
    display: inline-flex;
    align-items: flex-start;
```
Но придётся обернуть в контейнер, которым мы будем центрировать этот элемент
Ну и хорошо бы сделать `text-align: left` для пущей красоты)
![Screenshot 2023-09-30 at 13 04 51](https://github.com/kertio/frontend_course_rep1/assets/4070730/bee5d934-e966-419e-939d-9f96c75d9996)

2023-09-30 05:40 UTC, Grinv commented on 3-finio/images/icons/09 - HTML и CSS с наставником (Copy).zip
А это тут что делает?)

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +						<h3 class="posible-block__subtitle">Заранее планируйте предстоящие платежи и&nbsp;поступления средств. Тем самым,
subtitle - это не h3 :) Это впринципе не заголовок
Для сабтайтлов я предпочитаю использовать
```
<p role="doc-subtitle">text</p>
```
Но нужно быть осторожным: https://adrianroselli.com/2020/08/be-wary-of-doc-subtitle.html

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +				<div class="promo__wrapper d-flex-v">
Зачем столько вложенностей?
```html
<section class="promo container promo__wrapper d-flex-v">
   <h2>Text</h2>
</section>

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +					<p class="promo__desc">Автоматическая синхронизация данных с&nbsp;маркетплейсов позволит вам мгновенно получать все
А тут p использовал, молодец
И попробуй `text-wrap: balance`, тебе понравится)

2023-09-30 05:40 UTC, Grinv commented on 3-finio/layouts/promo.css
> +.promo-list__item-excel::before {
Молодец, что через before)
Кстати, можешь поиграться и с `::marker`. Это даже более семантически верно
https://css-tricks.com/almanac/selectors/m/marker/

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +							<li class="promo-list__header">Excel</li>
Это не является частью списка, поэтому из ul нужно вынести

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +			<div class="tarif-card__wrapper d-flex-h">
Карточки хорошо бы делать через тэг article

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +					<button class="btn btn__fill">Бесплатно 14 дней</button>
Поставь плиз для этого элемента `cursor: pointer`

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +						<div class="tarif-card__row">
![Screenshot 2023-09-30 at 13 23 28](https://github.com/kertio/frontend_course_rep1/assets/4070730/a9fb49c8-2571-4e7f-83ad-109abe0dc784)
Неровненько) примени `align-items: center`

2023-09-30 05:40 UTC, Grinv commented on 3-finio/css/components/slider.css
> +	background: url('../../images/slider/btn-left.svg') no-repeat 50%;
Я бы не делал их через псевдо-элементы. Всё-таки это полноценные кнопки. Поэтому лучше их сделать через тэг button

2023-09-30 05:40 UTC, Grinv commented on 3-finio/css/components/slider.css
> +		max-width: 578px;
Зачем такие сложности? У тебя 2 элемента одинаковой ширины. Так и задай
```html
<div style="display: flex">
   <div style="width: 100%">Block1</div>
   <div style="width: 100%">Block2</div>
</div>
```
![Screenshot 2023-09-30 at 13 34 58](https://github.com/kertio/frontend_course_rep1/assets/4070730/efa2d5ae-129d-435f-96fc-309d30c4925b)
а отступ внутри контейнера можешь уже при помощи padding настроить

2023-09-30 05:40 UTC, Grinv commented on 3-finio/css/components/socials.css
> +	background: url('../../images/icons/socials/tg.svg');
Ну, я про before говорил в рамках буллетов в списках)
Тут у нас не список и это не буллет, а просто иконка соц. сети, поэтому тут можно и через img :)

2023-09-30 05:40 UTC, Grinv commented on 3-finio/index.html
> +						<h3 class="safety__subtitle">Никакие события не&nbsp;скажутся на&nbsp;бесперебойной работе сервиса.</h3>
Это p, а не h3 :)

2023-09-30 05:40 UTC, Grinv commented on 3-finio/layouts/posible.css
> +	padding: 10px;
Мне не очень понятно, зачем тут padding

2023-09-30 05:41 UTC, Grinv commented
![Screenshot 2023-09-30 at 13 40 50](https://github.com/kertio/frontend_course_rep1/assets/4070730/ba77ceaa-4a91-4d2b-a437-c92a4724cef4)
Не забудь кликнуть и посмотреть скрытые комментарии)

2023-10-10 05:22 UTC, kertio commented on 3-finio/css/global.css
> +	cursor: url('../images/cursor.png'), auto;
в макете вместо простого курсора рука, поэтому я и взял какой по макету (самому не понравилось) )

2023-10-10 05:45 UTC, kertio commented on 3-finio/css/global.css
> +	max-width: calc(var(--container-width) + (var(--padding-container) * 2));
пытался рассчитать так, чтобы  размер страницы был с паддингами, чтобы размер компенсировался. ну тоесть страница 1440, добавляю паддинг небольшой чтобы при сжатии страница не прилипала к краям, но и размер из-за применения паддингов не стал меньше положенного)

2023-10-10 05:46 UTC, kertio commented on 3-finio/css/global.css
> +	max-width: calc(var(--container-width) + (var(--padding-container) * 2));
кстати box-sizing установлен для боди.

2023-10-10 05:57 UTC, kertio commented on 3-finio/index.html
> +	<div class="header-skewed-bg">xcv</div>
это я див потерял пока настраивал )

2023-10-10 09:28 UTC, kertio commented on 3-finio/index.html
> +			<button class="burger"></button>
А почему именно так?

2023-10-10 11:55 UTC, kertio commented on 3-finio/images/icons/09 - HTML и CSS с наставником (Copy).zip
упс)

2023-10-10 12:10 UTC, kertio commented on 3-finio/index.html
> +				<div class="promo__wrapper d-flex-v">
promo это сама секция, чтобы можно ее было покрасить фон   в синий цвет. а контейнер уже ограничивает размер этой секции. от одного дива избавился, а с одним дивом вся верстка ломается(

2023-10-10 12:13 UTC, kertio commented on 3-finio/index.html
> +					<p class="promo__desc">Автоматическая синхронизация данных с&nbsp;маркетплейсов позволит вам мгновенно получать все
супер. мне в первом недочете понравился.. везде поставил на длинных текстах где используется перенос:)

2023-10-11 10:13 UTC, kertio commented on 3-finio/layouts/promo.css
> +.promo-list__item-excel::before {
игрался игрался, в итоге так и не смог позиционировать элементы по центру. они не выравниваются никаким методом. но буду знать что такое есть)

2023-10-11 10:58 UTC, kertio commented on 3-finio/index.html
> +						<div class="tarif-card__row">
Даже и не заметил, хотя этот блок больше всего времени у меня отнял )

2023-10-11 12:59 UTC, kertio commented on 3-finio/layouts/posible.css
> +	padding: 10px;
для меня тоже это осталось загадкой) проверил, ни на что не влияет.

2023-10-30 08:20 UTC, AlariCode commented
В целом всё было исправлено. Добавил 1 замечание по сглаживанию шрифтов. Так же если будет время, можешь на планшетном разрешении сделать отображение 2-х тарифов друг за другом, так как позволяет ширина
![image](https://github.com/kertio/frontend_course_rep1/assets/2528600/a0c9eeae-342e-4141-940e-8dc631804bb3)

2023-10-30 08:20 UTC, AlariCode commented on 3-finio/css/normalize.css
> +	margin: 0;
Я бы добавил
-webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;

2023-10-31 16:41 UTC, merged